In [1]:
import numpy as np

### numpy属性

In [2]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print("矩阵的维度是：", array.ndim)
print("矩阵的形状：", array.shape)
print("矩阵的大小即元素个数：", array.size)

[[1 2 3]
 [4 5 6]]
矩阵的维度是： 2
矩阵的形状： (2, 3)
矩阵的大小即元素个数： 6


### numpy创建array

In [3]:
a = np.array([2, 23, 4])
b = np.array([2, 22, 3], dtype=np.int)
c = np.zeros((3, 4))
d = np.ones((3, 4), dtype=np.int16)
e = np.empty((3, 4))
f = np.arange(12).reshape((3, 4))
g = np.linspace(1, 10, 4).reshape((2, 2))

print(a)
print("矩阵中数据的类型为：", b.dtype)
print(c)
print(d)
print(e)
print(f)
print(g)

[ 2 23  4]
矩阵中数据的类型为： int32
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  4.]
 [ 7. 10.]]


### numpy基础运算

In [4]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
c = a - b
d = a + b
e = b**2
f = 10 * np.sin(a)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print("在b中有哪些是小于三的：", b < 3)

[10 20 30 40]
[0 1 2 3]
[10 19 28 37]
[10 21 32 43]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
在b中有哪些是小于三的： [ True  True  True False]


In [5]:
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape((2, 2))

print(a)
print(b)
print("逐个相乘：\n", a * b)
print("矩阵乘法：\n", np.dot(a, b))
print("矩阵乘法：\n", a.dot(b))

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
逐个相乘：
 [[0 1]
 [0 3]]
矩阵乘法：
 [[2 4]
 [2 3]]
矩阵乘法：
 [[2 4]
 [2 3]]


In [6]:
#产生一个由0到1的随机数生成的矩阵
a = np.random.random((2, 4))

#各种统计数据
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))
#axis代表在哪个维度上进行
print(np.sum(a, axis=1))
print(np.min(a, axis=0))

[[0.20137449 0.393676   0.87048039 0.55428528]
 [0.07741208 0.51267669 0.85018818 0.8889859 ]]
4.349079001316841
0.07741207561980346
0.8889859010765316
[2.01981616 2.32926285]
[0.07741208 0.393676   0.85018818 0.55428528]


### numpy高级基础运算

In [8]:
A = np.arange(14,2,-1).reshape((3,4))

print(A)
print("矩阵中最小值的索引：",np.argmin(A))
print("矩阵中最大值的索引：",np.argmax(A))
print("矩阵的平均值：",np.mean(A))
print("矩阵的平均值：",np.average(A))
print("矩阵的中位数：",np.median(A))
print("矩阵的累加：",np.cumsum(A))
print("矩阵每两个数的差：",np.diff(A))
print("多个array代表所有非零数的位置：",np.nonzero(A))
print("排序：\n",np.sort(A))
print("转置：\n",np.transpose(A))
print((A.T).dot(A))
print("如下：\n",np.clip(A,5,9))
print("A中所有元素的和：",A.sum())

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
矩阵中最小值的索引： 11
矩阵中最大值的索引： 0
矩阵的平均值： 8.5
矩阵的平均值： 8.5
矩阵的中位数： 8.5
矩阵的累加： [ 14  27  39  50  60  69  77  84  90  95  99 102]
矩阵每两个数的差： [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
多个array代表所有非零数的位置： (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
排序：
 [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
转置：
 [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
如下：
 [[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
A中所有元素的和： 102


### numpy索引

In [9]:
a = np.arange(3,15)
b = a.reshape((3,4))
c = np.linspace(0,20,5)
d = np.array(range(10))
e = np.ones((9,1))

print("np.arange的索引：")
print(a)
print(a[3])
print("\nreshape之后的索引：")
print(b)
print(b[2])
print(b[1,1])
print(b[1][1])
print(b[2,:])
print(b[:,1])
print(b[2,1:2])
for row in b:
    print(row)
for column in b.T:
    print(column)
print(b.flatten())
for item in b.flat:
    print(item)
print("\nnp.linspace的索引:")
print(c)
for i in c:
    print(i)
for i in range(5):
    print(c[i])
print("\nnp.array的索引:")
print(d)
for i in d:
    print(i)
    print(d)
for i in range(10):
    print(d[i])
print("\nnp.ones的索引：")
print(e)
for i in e:
    print(i)
for i in range(9):
    print(e[i])
for i in range(9):
    print(e[i][0])

np.arange的索引：
[ 3  4  5  6  7  8  9 10 11 12 13 14]
6

reshape之后的索引：
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
8
[11 12 13 14]
[ 4  8 12]
[12]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14

np.linspace的索引:
[ 0.  5. 10. 15. 20.]
0.0
5.0
10.0
15.0
20.0
0.0
5.0
10.0
15.0
20.0

np.array的索引:
[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4 5 6 7 8 9]
1
[0 1 2 3 4 5 6 7 8 9]
2
[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2 3 4 5 6 7 8 9]
4
[0 1 2 3 4 5 6 7 8 9]
5
[0 1 2 3 4 5 6 7 8 9]
6
[0 1 2 3 4 5 6 7 8 9]
7
[0 1 2 3 4 5 6 7 8 9]
8
[0 1 2 3 4 5 6 7 8 9]
9
[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9

np.ones的索引：
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
