In [1]:
from PIL import Image
import numpy as np

In [2]:
for i in range(60):
    j = str(i+396)
    infile = "RGB/"+j+".jpg"
    outfile = "GSI/"+str(i)+".jpg"
    
    im = Image.open(infile).convert("L")
    im = im.resize((256,256),Image.ANTIALIAS)
    im.save(outfile)

In [3]:
for i in range(1):
    outfile = "GSI/"+str(i)+".jpg"
    im = Image.open(outfile)
    temp = np.array(im)
    print(temp)

[[247 250 254 ... 239 239 239]
 [250 248 254 ... 239 239 239]
 [254 247 251 ... 239 239 239]
 ...
 [174 162 154 ... 220 223 225]
 [138 148 145 ... 222 223 224]
 [ 91  66  37 ... 223 223 222]]
